- name: Demonstrate ignore_errors in playbool
  hosts: centos
  tasks:
    - name: Print a fact variable
      ansible.builtin.debug:
        msg: "{{ testing }}"
      ignore_errors: true
      register: result
      failed_when: "'The task includes an option with an undefined variable' in result.msg"
    - name: Display a message
      ansible.builtin.debug:
        msg: This task ran successfully

